### ISSUE TITLE
likely versioning mistake

### ISSUE THREAD

**Issue by sbowman-mitre** [TUDelft-CNS-ATM/openap#14]
I think a small mistake occurred in the last release. In tagged version "Version 1.0" of OpenAP, the setup.py version remained unchanged (see below). And, the master branch also appears to be behind release 1.0 even though it should be ahead. 

https://github.com/junzis/openap/blob/6e68375e48d246c2247201c81bb83bae57db2dcf/setup.py#L33

**Comment by junzis** [comment]
I will make an update for that. Thanks!
