### ISSUE TITLE
missing dependency numdifftools

### ISSUE THREAD

**Issue by sbowman-mitre** [TUDelft-CNS-ATM/openap#15]
I believe `numdifftools` is also needed here as a dependency (for proper usage of opt.py code).

https://github.com/junzis/openap/blob/e7fef1b4b2fb2be41b16df385df42c68ba8f017e/setup.py#L90

**Comment by junzis** [comment]
The opt code is still very very basic, it is only a simple script so far. I am a bit ashamed to call it optimization module :sweat_smile:

We are making a better optimizer in a different project. I will incorporate that at some point later this year once it is ready. And the dependency will likely to be different.
