### ISSUE TITLE
The Fuel flow for aircraft ground movement 

### ISSUE THREAD

**Issue by strnam** [TUDelft-CNS-ATM/openap#16]
Thank you for open source the Aircraft Performance Model,

Can the API here, such as Fuel flow, be used for aircraft ground movement (with set altitude=0)?

**Comment by junzis** [comment]
For now, it is not possible with OpenAP. But it will be nice to have for the future.

Ground model is quite complicated since it involves APU, and there is not such data from the ICAO emission databank. Do you have any suggestions?
